package config

const CONFIG_TEMPLATE = `# GOAT Configuration (goat.yaml)
#
# This file is generated by GOAT (Golang Application Tracing).
# You may modify this file if you understand its purpose.
# After changing any field, re-run to update tracking results.
#
## Application name (default: current directory name)
appName: {{.AppName}}

## Application version (default: current branch's commit short hash)
## Before running "goat track" or "goat patch", ensure this version is correct.
## Only change when necessary.
appVersion: {{.AppVersion}}

## Old branch name (comparison base)
## Valid values:
## 1. Commit hash
## 2. Branch name
## 3. Tag name
## 4. "" or "HEAD" - refers to the current branch
## 5. "INIT" - indicates this is a new repository with no old branch
## Default: "main"
oldBranch: {{.OldBranch}}

## New branch name (comparison target)
## Valid values:
## 1. Commit hash
## 2. Branch name
## 3. Tag name
## 4. "" or "HEAD" - refers to the current branch
## Default: "HEAD"
## Note: newBranch should match the current HEAD
newBranch: {{.NewBranch}}

## Files and directories to ignore during tracking
ignores:{{range .Ignores}}
  - {{ . -}}
{{- end}}

## GOAT package configuration
## Package name used in imports
goatPackageName: {{.GoatPackageName}}

## Package alias used in code
goatPackageAlias: {{.GoatPackageAlias}}

## Path where GOAT package is installed in your project
goatPackagePath: {{.GoatPackagePath}}

## Tracking granularity (default: patch)
## Options:
## - line: Track changes at line level when modified
## - patch: Track changes at patch level (diff patches in same scope)
## - scope: Track changes at scope level when any part is modified
## - func: Track changes at function level when any part is modified
granularity: {{.Granularity}}

## Diff precision level (1-3, default: 1)
## Level 1: Uses git blame for highest precision but slowest performance
## Level 2: Uses git diff with file rename/move tracking; medium precision,
##          much better performance (100x faster than level 1)
## Level 3: Uses git diff without rename/move tracking; lowest precision,
##          best performance (1-10x faster than level 2)
diffPrecision: {{.DiffPrecision}}

## Number of processing threads (default: 1)
threads: {{.Threads}}

## Race detection (default: false)
## true: Enable race detection (worse performance)
## false: Disable race detection (better performance)
race: {{.Race}}

## Main packages to track (default: all)
## Specify relative paths to main packages from project root
## Examples:
## - "*" (track all main packages)
## - "cmd/server" (track only the main package in cmd/server)
## - "cmd/client,cmd/server" (track multiple specific packages)
mainEntries:{{range .MainEntries}}
  - "{{. -}}"
  {{- end}}

## Gofmt printer configuration (same as printer.Config)
## Mode options: none, useSpaces, tabIndent, sourcePos, rawFormat
## Default: "useSpaces,tabIndent"
printerConfigMode:{{range .PrinterConfigMode}}
  - "{{. -}}"
  {{- end}}

## Tab width for printer configuration (default: 8)
printerConfigTabwidth: {{.PrinterConfigTabwidth}}

## Indentation level for printer configuration (default: 0)
printerConfigIndent: {{.PrinterConfigIndent}}

## Data type for tracking (default: truth)
## Options: truth, count
dataType: {{.DataType}}

## Enable verbose output (default: false)
verbose: {{.Verbose}}
`
